[[libiio]]
arch = "aarch64"
git-tree-sha1 = "b19cb6eb5d2f44866bda4048f95ac71b7246e1b6"
os = "macos"

    [[libiio.download]]
    sha256 = "efdfe1ce051b7c2eba516b22602aee44892c2fcc99647ee285b73ce62f70a4c2"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.24.0+0/libiio.v0.24.0.aarch64-apple-darwin.tar.gz"
[[libiio]]
arch = "aarch64"
git-tree-sha1 = "1d373e0fab5250e3666b0fe2b021f2a0bba4a2a5"
libc = "glibc"
os = "linux"

    [[libiio.download]]
    sha256 = "f2a02ffb7846395f863f66f6f33273bac0f2262e6fbb5b1f623b70c90f5ea222"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.24.0+0/libiio.v0.24.0.aarch64-linux-gnu.tar.gz"
[[libiio]]
arch = "aarch64"
git-tree-sha1 = "1d654f622b6e4c21657bdfec9d99c3fa494ff485"
libc = "musl"
os = "linux"

    [[libiio.download]]
    sha256 = "1574ccf7e11f97456c8d38abd12568c690623209f1ad6c5376a610bb24c1fa21"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.24.0+0/libiio.v0.24.0.aarch64-linux-musl.tar.gz"
[[libiio]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "076c2cd5899bf4983520296a35c5fdb9ebe37c91"
libc = "glibc"
os = "linux"

    [[libiio.download]]
    sha256 = "ac04a6438834d635448a25b0e9c7d24a5996fc04cbe5955c38ff4e8632dc226e"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.24.0+0/libiio.v0.24.0.armv6l-linux-gnueabihf.tar.gz"
[[libiio]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "91eeaa67688aaed9621cbc3a6b819a768cca8a1c"
libc = "musl"
os = "linux"

    [[libiio.download]]
    sha256 = "01074f42de22238b13c20f03003a56be7051dcacdc4e001a393764844e4be23b"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.24.0+0/libiio.v0.24.0.armv6l-linux-musleabihf.tar.gz"
[[libiio]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2868b03b67867eaa6aecffb24c4b1ff869ea94bd"
libc = "glibc"
os = "linux"

    [[libiio.download]]
    sha256 = "e89821d5e7959af2b940bca06b26e737df287f57bf7eeaeffb658f7ca48827f7"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.24.0+0/libiio.v0.24.0.armv7l-linux-gnueabihf.tar.gz"
[[libiio]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0a21dd243570692a752f072e0c31fa21fd662412"
libc = "musl"
os = "linux"

    [[libiio.download]]
    sha256 = "f70e28fa386f6cb099229352fec3cc18f845717acf6a24c50cbc86644af437e7"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.24.0+0/libiio.v0.24.0.armv7l-linux-musleabihf.tar.gz"
[[libiio]]
arch = "i686"
git-tree-sha1 = "90dbe6e7e11ac53bb32b18637670f83af1b2ebf7"
libc = "glibc"
os = "linux"

    [[libiio.download]]
    sha256 = "0fb5405275a0ba4e45642617fc9285647b375436284c0dde5a57e6e9a49326c3"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.24.0+0/libiio.v0.24.0.i686-linux-gnu.tar.gz"
[[libiio]]
arch = "i686"
git-tree-sha1 = "f0d0c10a2c6f7f3efeb8e4194d27fa529e247bd5"
libc = "musl"
os = "linux"

    [[libiio.download]]
    sha256 = "ae10776a9ffff22105f91ee019ef86173857b7bb5237c6fda83b1d8adc5c6973"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.24.0+0/libiio.v0.24.0.i686-linux-musl.tar.gz"
[[libiio]]
arch = "i686"
git-tree-sha1 = "ffc7e4894b34d516f6ee69eae215dab85aee4787"
os = "windows"

    [[libiio.download]]
    sha256 = "6c4025163f0599b82a74aec4a18f07845d685dbf251c2775fcf90062f5fba400"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.24.0+0/libiio.v0.24.0.i686-w64-mingw32.tar.gz"
[[libiio]]
arch = "powerpc64le"
git-tree-sha1 = "d86f5799dd23bc2d5841eda1ddb51576da3c48d9"
libc = "glibc"
os = "linux"

    [[libiio.download]]
    sha256 = "5f1441a91a6228193bafe29c97814f4bcb31eb6dd9d2d07de62dcee5f77c392d"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.24.0+0/libiio.v0.24.0.powerpc64le-linux-gnu.tar.gz"
[[libiio]]
arch = "x86_64"
git-tree-sha1 = "9ab6597dd56b0412b4b18460593df98dfde5e68e"
os = "macos"

    [[libiio.download]]
    sha256 = "0c23d50ab58f91e72621343f25835558d265cbddfb848b57f41e21f48410c029"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.24.0+0/libiio.v0.24.0.x86_64-apple-darwin.tar.gz"
[[libiio]]
arch = "x86_64"
git-tree-sha1 = "e4dfef6b1ca9ea97546aa348fda31194be0068c4"
libc = "glibc"
os = "linux"

    [[libiio.download]]
    sha256 = "a9cdf2a922d1e6d1689f9699b5dbda8f4f42214596396fb437034573d3852d5f"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.24.0+0/libiio.v0.24.0.x86_64-linux-gnu.tar.gz"
[[libiio]]
arch = "x86_64"
git-tree-sha1 = "77ef8d6a551e7135ab4ac0d7f0e4c0b3b719eca6"
libc = "musl"
os = "linux"

    [[libiio.download]]
    sha256 = "7c5e84a27979bd7431061e8ba2ac196bc91c0e540e7dfe60bb4c0ab6b8dea5bc"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.24.0+0/libiio.v0.24.0.x86_64-linux-musl.tar.gz"
[[libiio]]
arch = "x86_64"
git-tree-sha1 = "814fd76683c6f3fc77329869b80242d6becd32fc"
os = "freebsd"

    [[libiio.download]]
    sha256 = "d7f814f4f865c200dc3064494652f10175f8244283f5552b8db660fe27d2d5f0"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.24.0+0/libiio.v0.24.0.x86_64-unknown-freebsd.tar.gz"
[[libiio]]
arch = "x86_64"
git-tree-sha1 = "51b1de5183d61990b15b3399b386dacd1b4b3daf"
os = "windows"

    [[libiio.download]]
    sha256 = "55a2155d15fcb49d487588a36c71f1b9566f62fef4d2a120860ea0224727abd5"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.24.0+0/libiio.v0.24.0.x86_64-w64-mingw32.tar.gz"
