[[libiio]]
arch = "aarch64"
git-tree-sha1 = "ac4dc45720442ba6990c83a8b67c88005180d1e6"
os = "macos"

    [[libiio.download]]
    sha256 = "f6b9643811de03fd071c53207211016871fb2747e7e738c28124927a5503c0aa"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.23.0+0/libiio.v0.23.0.aarch64-apple-darwin.tar.gz"
[[libiio]]
arch = "x86_64"
git-tree-sha1 = "e27f948662aa10b58cf1ccf9d6124e80cfb72f91"
os = "macos"

    [[libiio.download]]
    sha256 = "11f66cb5a180e05dff48d9784e7fecfdb556814bc940d883d756f8fc2b9b87cb"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.23.0+0/libiio.v0.23.0.x86_64-apple-darwin.tar.gz"
[[libiio]]
arch = "aarch64"
git-tree-sha1 = "2ad87ba5c507de8861dc9c03b51b02c3738269c5"
libc = "glibc"
os = "linux"

    [[libiio.download]]
    sha256 = "230d178cb93f34b251983b90fddac447b111e2a704555ef30bff5aa6bc3ec112"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.23.0+0/libiio.v0.23.0.aarch64-linux-gnu.tar.gz"
[[libiio]]
arch = "aarch64"
git-tree-sha1 = "845e0d82c7204b3e42743f39daab1cae5c1ec89a"
libc = "musl"
os = "linux"

    [[libiio.download]]
    sha256 = "6e3b315a492033099524bf1435366eaa6e1d33cda5671156cd583bfd5a367e52"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.23.0+0/libiio.v0.23.0.aarch64-linux-musl.tar.gz"
[[libiio]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cbe3660a50f80e5836dbd7bd4098604c45a4bcf0"
libc = "glibc"
os = "linux"

    [[libiio.download]]
    sha256 = "48ef05dc88d8bb13fd39941978c1b6ff5cdcbeb8057ba9dcedf4c97e67b3a8bb"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.23.0+0/libiio.v0.23.0.armv6l-linux-gnueabihf.tar.gz"
[[libiio]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0eb910de8052dea64ec28a172039aa65fed20f3e"
libc = "musl"
os = "linux"

    [[libiio.download]]
    sha256 = "45c019f93e73daf14dfa7f730931ca4d81f09ec31eaea6752ad8ffd14b0247f3"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.23.0+0/libiio.v0.23.0.armv6l-linux-musleabihf.tar.gz"
[[libiio]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6ad699a2c5e5c63d4d2b39ca9b807f987ca1bb88"
libc = "glibc"
os = "linux"

    [[libiio.download]]
    sha256 = "08afba46c72c6a40d860303f8190bac1fefb3380e8bb7ba20bfbe3d060a1f38f"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.23.0+0/libiio.v0.23.0.armv7l-linux-gnueabihf.tar.gz"
[[libiio]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "21088bea011d2937888ebf4ce9cb5cdafe4ee03d"
libc = "musl"
os = "linux"

    [[libiio.download]]
    sha256 = "c5d91229c69164bc7a3a4f6b205699940c083b8e3c7c0053ff324a025dc70d71"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.23.0+0/libiio.v0.23.0.armv7l-linux-musleabihf.tar.gz"
[[libiio]]
arch = "i686"
git-tree-sha1 = "bbfe6605d4a3c0b342cd18913fa6d597a4bdda7b"
libc = "glibc"
os = "linux"

    [[libiio.download]]
    sha256 = "745db4cb9f27a3a07f3c23ed29a1157ee212ce57e19b258f660e2ec726cea9a9"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.23.0+0/libiio.v0.23.0.i686-linux-gnu.tar.gz"
[[libiio]]
arch = "i686"
git-tree-sha1 = "bc6e7fcc265d17bdcdaf85abbe65c171ce44827c"
libc = "musl"
os = "linux"

    [[libiio.download]]
    sha256 = "62dfb20a9c3593c758b8bdcb9647de79e08513e9f822ec8c683389598264e670"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.23.0+0/libiio.v0.23.0.i686-linux-musl.tar.gz"
[[libiio]]
arch = "i686"
git-tree-sha1 = "ab8cf3a011ec99eebc176eecd81aaaf6589660b6"
os = "windows"

    [[libiio.download]]
    sha256 = "a8bef9d35897416ca45c479497e3b45c65d5a99309e5a8650f9f660eb6adc302"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.23.0+0/libiio.v0.23.0.i686-w64-mingw32.tar.gz"
[[libiio]]
arch = "powerpc64le"
git-tree-sha1 = "ef73a17962461d341c729af2b775de626bf57896"
libc = "glibc"
os = "linux"

    [[libiio.download]]
    sha256 = "df0df3a6b110e50a15a8718a3e5865036f3c10ce0c84283ae00e9facb87133cf"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.23.0+0/libiio.v0.23.0.powerpc64le-linux-gnu.tar.gz"
[[libiio]]
arch = "x86_64"
git-tree-sha1 = "d043316690bdcd70f041b815031e50cda4024d51"
libc = "glibc"
os = "linux"

    [[libiio.download]]
    sha256 = "85f8e9c57a01a1652e99abd262cd3e53836ee51cd81362c67699755cd58b048f"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.23.0+0/libiio.v0.23.0.x86_64-linux-gnu.tar.gz"
[[libiio]]
arch = "x86_64"
git-tree-sha1 = "1fd1ee00d6b4ec8d54df557599f94513e3826946"
libc = "musl"
os = "linux"

    [[libiio.download]]
    sha256 = "c4b220446a22d881ce4f9b8678d8bfabde78af3efbb8e053f1708a7284f04c8f"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.23.0+0/libiio.v0.23.0.x86_64-linux-musl.tar.gz"
[[libiio]]
arch = "x86_64"
git-tree-sha1 = "27d814fc488b34feca62b74b45c7a5b0f8e4bc21"
os = "freebsd"

    [[libiio.download]]
    sha256 = "f4c2c4c3101f0c9bb3475878eb0a07676886c4c3a4a220bed93919845a1045ec"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.23.0+0/libiio.v0.23.0.x86_64-unknown-freebsd.tar.gz"
[[libiio]]
arch = "x86_64"
git-tree-sha1 = "5e11d595f21a5f465e6ded834b912da3adc42b22"
os = "windows"

    [[libiio.download]]
    sha256 = "1eb323133a09938e58bb1805c6ccfc1752a318b799f7f509224d1fcd2b7c4ebc"
    url = "https://github.com/JuliaBinaryWrappers/libiio_jll.jl/releases/download/libiio-v0.23.0+0/libiio.v0.23.0.x86_64-w64-mingw32.tar.gz"
